"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const register_1 = __importDefault(require("../controller/register"));
const login_1 = __importDefault(require("../controller/login"));
const createNewList_1 = __importDefault(require("../controller/createNewList"));
const saveActvity_1 = __importDefault(require("../controller/saveActvity"));
const fetchNearby_1 = __importDefault(require("../controller/fetchNearby"));
const express_1 = require("express");
const fetchFvaourites_1 = __importDefault(require("../controller/fetchFvaourites"));
const fetchLists_1 = __importDefault(require("../controller/fetchLists"));
const SaveFavorites_1 = __importDefault(require("../controller/SaveFavorites"));
const removeFavourite_1 = __importDefault(require("../controller/removeFavourite"));
const deleteList_1 = __importDefault(require("../controller/deleteList"));
const authenticateJwt_1 = require("../middleWare/authenticateJwt");
const router = (0, express_1.Router)();
router.post('/register', register_1.default);
router.post('/login', login_1.default);
router.post('/createNewList', createNewList_1.default);
router.post('/saveActivities', saveActvity_1.default);
router.post('/fetchNearby', fetchNearby_1.default);
router.post('/fetchFavourites', authenticateJwt_1.authenticateJWT, fetchFvaourites_1.default);
router.post('/fetchLists', authenticateJwt_1.authenticateJWT, fetchLists_1.default);
router.post('/saveFavourites', SaveFavorites_1.default);
router.post('/removeFavourites', removeFavourite_1.default);
router.post('/deleteList', deleteList_1.default);
exports.default = router;
